# Generated by Django 2.0.1 on 2018-01-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0005_book_pubished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoproject.City'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoproject.Book'),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='bookstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demoproject.BookStore'),
        ),
    ]
