# Generated by Django 2.0 on 2018-01-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '井通钱包',
            },
        ),
    ]
