# Generated by Django 2.0 on 2018-01-18 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingtum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='wallet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jingtum.Wallet'),
        ),
    ]
